# Generated by Django 6.0.5 on 2026-05-17 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Internal name for the page. If multiple pages of the same order and priority are being displayed, they will be shown in alphanumeric order by name.', max_length=80, unique=True)),
                ('order', models.IntegerField(default=1000, help_text='Hint for ordering of pages in the carousel')),
                ('enabled', models.BooleanField(default=False, help_text='Include this page in the carousel?')),
                ('condition', models.CharField(choices=[('A', 'Always'), ('O', 'Only when open'), ('C', 'Only when closed')], default='A', help_text='When should this page be displayed?', max_length=1)),
                ('display_after', models.DateTimeField(blank=True, help_text="Don't display this page until after this time", null=True)),
                ('display_until', models.DateTimeField(blank=True, help_text='Stop displaying this page after this time', null=True)),
                ('display_time', models.IntegerField(default=30, help_text='Display the page for this number of seconds')),
                ('priority', models.CharField(choices=[('U', 'Urgent'), ('N', 'Normal')], default='N', help_text='Priority for this page. Urgent pages suppress the display of all other non-urgent pages.', max_length=1)),
                ('title', models.CharField(blank=True, help_text='Title to be shown at the top of the display, between the logo and the clock', max_length=80)),
                ('template', models.CharField(blank=True, choices=[('Display', 'Blank display'), ('OnTap', 'Drinks on tap'), ('CansAndBottles', 'Craft cans and bottles'), ('Wines', 'Wines and wine cans'), ('WinesAndSpirits', 'Wines and spirits'), ('SpiritsAndMixers', 'Spirits and mixers'), ('ClubMate', 'Club Mate'), ('SoftDrinks', 'Soft drinks'), ('Snacks', 'Snacks'), ('Progress', 'Event progress'), ('ProgressFacts', 'Bar Fun Facts'), ('OpeningTimes', 'Bar opening times')], help_text='Programmed template for the page', max_length=80)),
                ('content', models.TextField(blank=True, help_text='Content for the page if no template is chosen. Markdown or HTML')),
            ],
            options={
                'ordering': ('order', 'slug'),
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, help_text="Used to form the URL for the page. Lower-case, no spaces, do not include leading or trailing '/'. Blank for front page.", max_length=80, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_time', models.DateTimeField(help_text='Time we open')),
                ('closing_time', models.DateTimeField(help_text='Time we close')),
                ('weight', models.FloatField(help_text='Expected busyness of session')),
                ('comment', models.CharField(blank=True, help_text='Displayed on web interface; not private!', max_length=100)),
            ],
            options={
                'ordering': ('opening_time',),
                'constraints': [models.CheckConstraint(condition=models.Q(('closing_time__gt', models.F('opening_time'))), name='ends_after_start')],
            },
        ),
    ]
