# Generated by Django 6.0.5 on 2026-06-17 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emf', '0002_alter_page_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='KioskOrderRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
